### ISSUE TITLE
macOS run error

### ISSUE THREAD

**Issue by chifandeyu** [MixinNetwork/flutter-app#663]
![image](https://user-images.githubusercontent.com/15946864/171661923-1c1b822f-681e-4a55-8f77-382af3f56c00.png)

flutter run -d macOS

```
Launching lib/main.dart on macOS in debug mode...
objc[34838]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1f77fa098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1046082c8). One of the two will be used. Which one is undefined.
objc[34838]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1f77fa0e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104608318). One of the two will be used. Which one is undefined.
objc[34838]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1f77f9eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1046084f8). One of the two will be used. Which one is undefined.
objc[34838]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1f77f9f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104608548). One of the two will be used. Which one is undefined.
objc[34838]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1f77f9f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104608598). One of the two will be used. Which one is undefined.
objc[34838]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1f77f9fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1046085e8). One of the two will be used. Which one is undefined.
objc[34838]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1f77f9ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104608638). One of the two will be used. Which one is undefined.
objc[34838]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1f77fa040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104608688). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-001A44AA2EF3001E }
{ platform:macOS, arch:x86_64, id:00008103-001A44AA2EF3001E }
/Users/yuchang.xu/workspace/flutter-app/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 12.2. (in target 'sqlite3' from project 'Pods')
Building macOS application...                                           
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image-4.2.1/lib/src/extended_image.dart:774:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image-4.2.1/lib/src/extended_image.dart:782:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image-4.2.1/lib/src/extended_image.dart:863:26: Warning: Operand of null-aware operation '!' has type 'SemanticsBinding' which excludes null.
 - 'SemanticsBinding' is from 'package:flutter/src/semantics/binding.dart' ('../../flutter-2/packages/flutter/lib/src/semantics/binding.dart').
        SemanticsBinding.instance!.accessibilityFeatures.invertColors;
                         ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart:26:21: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter-2/packages/flutter/lib/src/painting/binding.dart').
    PaintingBinding.instance?.imageCache?.clear();
                    ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart:27:21: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter-2/packages/flutter/lib/src/painting/binding.dart').
    PaintingBinding.instance?.imageCache?.clearLiveImages();
                    ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart:40:28: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter-2/packages/flutter/lib/src/painting/binding.dart').
    return PaintingBinding.instance?.imageCache;
                           ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:28:30: Warning: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter-2/packages/flutter/lib/src/painting/binding.dart').
      return PaintingBinding.instance!.imageCache!;
                             ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:28:40: Warning: Operand of null-aware operation '!' has type 'ImageCache' which excludes null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('../../flutter-2/packages/flutter/lib/src/painting/image_cache.dart').
      return PaintingBinding.instance!.imageCache!;
                                       ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:97:39: Warning: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter-2/packages/flutter/lib/src/painting/binding.dart').
      () => load(key, PaintingBinding.instance!.instantiateImageCodec),
                                      ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:42:29: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    _state = WidgetsBinding.instance!.lifecycleState;
                            ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:43:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:52:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../flutter-2/.pub-cache/git/bitsdojo_window-78faaa6440c7fee146258bb0ef3336c33ed4555d/bitsdojo_window_linux/lib/src/bitsdojo_window_linux_real.dart:14:20: Warning: Operand of null-aware operation '!' has type
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.waitUntilFirstFrameRasterized.then((value) {
                   ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_macos-0.1.0/lib/src/bitsdojo_window_macos_real.dart:13:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.waitUntilFirstFrameRasterized.then((value) {
                   ^
../../flutter-2/.pub-cache/git/bitsdojo_window-78faaa6440c7fee146258bb0ef3336c33ed4555d/bitsdojo_window_windows/lib/src/bitsdojo_window_windows_real.dart:17:20: Warning: Operand of null-aware operation '!' has type
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.waitUntilFirstFrameRasterized.then((value) {
                   ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window-0.1.1+1/lib/src/widgets/mouse_state_builder.dart:60:30: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter-2/packages/flutter/lib/src/widgets/binding.dart').
              WidgetsBinding.instance!.addPostFrameCallback((_) {
                             ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:126:28: Warning: Operand of null-aware operation '?.' has type 'RendererBinding' which excludes null.
 - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('../../flutter-2/packages/flutter/lib/src/rendering/binding.dart').
    assert(RendererBinding.instance?.renderView != null);
                           ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:127:50: Warning: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null.
 - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('../../flutter-2/packages/flutter/lib/src/rendering/binding.dart').
    var clipRect = Offset.zero & RendererBinding.instance!.renderView.size;
                                                 ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:170:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter-2/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
                         ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:193:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter-2/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!
                     ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart:439:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter-2/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart:486:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter-2/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../flutter-2/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.2.3/lib/src/positioned_list.dart:312:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter-2/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
Syncing files to device macOS...                                   145ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:52297/oL0A4xVSn5E=/

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Builder(dirty, dependencies: [MediaQuery,
_InheritedProviderScope<SettingCubit?>]):
invalid value for brightness. SettingState(null, null, null, null, null, null, null)
'package:flutter_app/bloc/setting_cubit.dart':
Failed assertion: line 127 pos 16: 'false'

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///Users/yuchang.xu/workspace/flutter-app/lib/app.dart:200:18

When the exception was thrown, this was the stack:
#2      SettingCubit.brightness (package:flutter_app/bloc/setting_cubit.dart:127:16)
#3      _App.build.<anonymous closure> (package:flutter_app/app.dart:225:64)
#4      _MaterialAppState._materialBuilder.<anonymous closure> (package:flutter/src/material/app.dart:896:39)
#5      Builder.build (package:flutter/src/widgets/basic.dart:7371:48)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4876:49)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
...     Normal element mounting (92 frames)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#105    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#107    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#108    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#109    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#110    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#111    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#112    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:52297/oL0A4xVSn5E=/
```

**Comment by crossle** [comment]
Run `flutter doctor` and check the flutter version.
Only support Flutter 3

**Comment by chifandeyu** [comment]
> 

But now I use flutter 3.0.1 and windows platform still report the error.
